version: "3.9"

services:
  mern:
    container_name: mern-social
    image: mern-social
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
    environment:
      - PORT=$PORT
      - MONGO_HOST=$MONGO_HOST
      - JWT_SECRET=$JWT_SECRET

  mongo:
    container_name: mongo
    image: mongo:3.6.3
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - MONGO_HOST=$MONGO_HOST
      - JWT_SECRET=$JWT_SECRET

volumes:
  mongodata:

networks:
  backend:
     internal: true
  frontend:
