version: "3.9"

services:
  mern:
    container_name: mern-social
    image: mern-social
    build: .
    env_file: .env
    environment:
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo:3.6.3
    env_file: .env
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  mongodata:

networks:
  backend:
     internal: true
  frontend:
